const data = {
  products: [
    {
        name: 'Sidney Crosby Pittsburgh  Penguins Adidas Home Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'center',
        player: 'Crosby, Sidney',
        playerNum: 87,
        style: 'Home',
        size: 's',
        year: 2021,
        image: '../img/penguins/jscrosby87ho2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.8',
        numReviews: 102,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Sidney Crosby in action. Whether you\'re behind the glass or the TV screen, this Sidney Crosby Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Sidney Crosby\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Sidney Crosby Pittsburgh Penguins Adidas Away Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'center',
        player: 'Crosby, Sidney',
        playerNum: 87,
        style: 'Away',
        size: 's',
        year: 2021,
        image: '../img/penguins/jscrosby87aw2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.7',
        numReviews: 92,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Sidney Crosby in action. Whether you\'re behind the glass or the TV screen, this Sidney Crosby Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Sidney Crosby\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Sidney Crosby Pittsburgh Penguins Adidas Reverse Retro Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'center',
        player: 'Crosby, Sidney',
        playerNum: 87,
        style: 'Reverse Retro',
        size: 's',
        year: 2021,
        image: '../img/penguins/jscrosby87rr2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.9',
        numReviews: 63,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Sidney Crosby in action. Whether you\'re behind the glass or the TV screen, this Sidney Crosby Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Sidney Crosby\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Evgeni Malkin Pittsburgh Penguins Adidas Home Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'center',
        player: 'Malkin, Evgeni',
        playerNum: 71,
        style: 'Home',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsmalkin71ho2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.7',
        numReviews: 190,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Evgeni Malkin in action. Whether you\'re behind the glass or the TV screen, this Evgeni Malkin Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Evgeni Malkin\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Evgeni Malkin Pittsburgh Penguins Adidas Away Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'center',
        player: 'Malkin, Evgeni',
        playerNum: 71,
        style: 'Away',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsmalkin71aw2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.8',
        numReviews: 89,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Evgeni Malkin in action. Whether you\'re behind the glass or the TV screen, this Evgeni Malkin Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Evgeni Malkin\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Evgeni Malkin Pittsburgh Penguins Adidas Reverse Retro Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'center',
        player: 'Malkin, Evgeni',
        playerNum: 71,
        style: 'Reverse Retro',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsmalkin71rr2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.8',
        numReviews: 112,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Evgeni Malkin in action. Whether you\'re behind the glass or the TV screen, this Evgeni Malkin Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Evgeni Malkin\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Jake Guentzel Pittsburgh Penguins Adidas Home Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'winger',
        player: 'Guentzel, Jake',
        playerNum: 59,
        style: 'Home',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsguentzel59ho2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.3',
        numReviews: 145,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Jake Guentzel in action. Whether you\'re behind the glass or the TV screen, this Jake Guentzel Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Jake Guentzel\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Jake Guentzel Pittsburgh Penguins Adidas Away Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'winger',
        player: 'Guentzel, Jake',
        playerNum: 59,
        style: 'Away',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsguentzel59aw2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.4',
        numReviews: 78,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Jake Guentzel in action. Whether you\'re behind the glass or the TV screen, this Jake Guentzel Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Jake Guentzel\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Jake Guentzel Pittsburgh Penguins Adidas Reverse Retro Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'wing',
        player: 'Guentzel, Jake',
        playerNum: 59,
        style: 'Reverse Retro',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsguentzel59rr2021.jpg',
        price: 229.99,
        countInStock: 10,
        brand: 'Adidas',
        rating: '4.0',
        numReviews: 100,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Jake Guentzel in action. Whether you\'re behind the glass or the TV screen, this Jake Guentzel Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Jake Guentzel\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Kasperi Kapanen Pittsburgh Penguins Adidas Home Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'winger',
        player: 'Kapanen, Kasperi',
        playerNum: 42,
        style: 'Home',
        size: 's',
        year: 2021,
        image: '../img/penguins/jskapanen42ho2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.4',
        numReviews: 69,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Kasperi Kapanen in action. Whether you\'re behind the glass or the TV screen, this Kasperi Kapanen Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Kasperi Kapanen\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Kasperi Kapanen Pittsburgh Penguins Adidas Away Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'winger',
        player: 'Kapanen, Kasperi',
        playerNum: 42,
        style: 'Away',
        size: 's',
        year: 2021,
        image: '../img/penguins/jskapanen42aw2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.2',
        numReviews: 45,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Kasperi Kapanen in action. Whether you\'re behind the glass or the TV screen, this Kasperi Kapanen Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Kasperi Kapanen\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Kasperi Kapanen Pittsburgh Penguins Adidas Reverse Retro Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'winger',
        player: 'Kapanen, Kasperi',
        playerNum: 42,
        style: 'Reverse Retro',
        size: 's',
        year: 2021,
        image: '../img/penguins/jskapanen42rr2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.8',
        numReviews: 32,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Kasperi Kapanen in action. Whether you\'re behind the glass or the TV screen, this Kasperi Kapanen Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Kasperi Kapanen\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Jason Zucker Pittsburgh Penguins Adidas Home Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'winger',
        player: 'Zucker, Jason',
        playerNum: 16,
        style: 'Home',
        size: 's',
        year: 2021,
        image: '../img/penguins/jszucker16ho2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.9',
        numReviews: 75,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Jason Zucker in action. Whether you\'re behind the glass or the TV screen, this Jason Zucker Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Jason Zucker\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Jason Zucker Pittsburgh Penguins Adidas Away Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'winger',
        player: 'Zucker, Jason',
        playerNum: 16,
        style: 'Away',
        size: 's',
        year: 2021,
        image: '../img/penguins/jszucker16aw2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.6',
        numReviews: 43,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Jason Zucker in action. Whether you\'re behind the glass or the TV screen, this Jason Zucker Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Jason Zucker\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Jason Zucker Pittsburgh Penguins Adidas Reverse Retro Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'winger',
        player: 'Zucker, Jason',
        playerNum: 16,
        style: 'Reverse Retro',
        size: 's',
        year: 2021,
        image: '../img/penguins/jszucker16rr2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.2',
        numReviews: 56,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Jason Zucker in action. Whether you\'re behind the glass or the TV screen, this Jason Zucker Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Jason Zucker\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Bryan Rust Pittsburgh Penguins Adidas Home Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'winger',
        player: 'Rust, Bryan',
        playerNum: 17,
        style: 'Home',
        size: 's',
        year: 2021,
        image: '../img/penguins/jszucker16ho2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.6',
        numReviews: 89,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Bryan Rust in action. Whether you\'re behind the glass or the TV screen, this Bryan Rust Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Bryan Rust\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Bryan Rust Pittsburgh Penguins Adidas Away Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'winger',
        player: 'Rust, Bryan',
        playerNum: 17,
        style: 'Away',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsrust17aw2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.4',
        numReviews: 99,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Bryan Rust in action. Whether you\'re behind the glass or the TV screen, this Bryan Rust Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Bryan Rust\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Bryan Rust Pittsburgh Penguins Adidas Reverse Retro Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'winger',
        player: 'Rust, Bryan',
        playerNum: 17,
        style: 'Reverse Retro',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsrust17rr2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.1',
        numReviews: 66,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Bryan Rust in action. Whether you\'re behind the glass or the TV screen, this Bryan Rust Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Bryan Rust\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
{
        name: 'Kris Letang Pittsburgh Penguins Adidas Home Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'defence',
        player: 'Letang, Kris',
        playerNum: 58,
        style: 'Home',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsletang58ho2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.8',
        numReviews: 61,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Kris Letang in action. Whether you\'re behind the glass or the TV screen, this Kris Letang Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Kris Letang\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Kris Letang Pittsburgh Penguins Adidas Away Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'defence',
        player: 'Letang, Kris',
        playerNum: 58,
        style: 'Away',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsletang58aw2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.7',
        numReviews: 132,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Kris Letang in action. Whether you\'re behind the glass or the TV screen, this Kris Letang Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Kris Letang\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Kris Letang Pittsburgh Penguins Adidas Reverse Retro Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'defence',
        player: 'Letang, Kris',
        playerNum: 58,
        style: 'Reverse Retro',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsletang58rr2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.5',
        numReviews: 123,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Kris Letang in action. Whether you\'re behind the glass or the TV screen, this Kris Letang Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Kris Letang\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
{
        name: 'Brian Dumoulin Pittsburgh Penguins Adidas Home Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'defence',
        player: 'Dumoulin, Brian',
        playerNum: 8,
        style: 'Home',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsdumoulin8ho2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.6',
        numReviews: 52,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Brian Dumoulin in action. Whether you\'re behind the glass or the TV screen, this Brian Dumoulin Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Brian Dumoulin\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Brian Dumoulin Pittsburgh Penguins Adidas Away Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'defence',
        player: 'Dumoulin, Brian',
        playerNum: 8,
        style: 'Away',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsdumoulin8aw2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.4',
        numReviews: 74,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Brian Dumoulin in action. Whether you\'re behind the glass or the TV screen, this Brian Dumoulin Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Brian Dumoulin\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Brian Dumoulin Pittsburgh Penguins Adidas Reverse Retro Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'defence',
        player: 'Dumoulin, Brian',
        playerNum: 8,
        style: 'Reverse Retro',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsdumoulin8rr2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '2.3',
        numReviews: 12,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Brian Dumoulin in action. Whether you\'re behind the glass or the TV screen, this Brian Dumoulin Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Brian Dumoulin\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
{
        name: 'Tristian Jarry Pittsburgh Penguins Adidas Home Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'goalie',
        player: 'Jarry, Tristian',
        playerNum: 35,
        style: 'Home',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsjarry35ho2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.7',
        numReviews: 90,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Tristian Jarry in action. Whether you\'re behind the glass or the TV screen, this Tristian Jarry Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Tristian Jarry\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Tristian Jarry Pittsburgh Penguins Adidas Away Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'goalie',
        player: 'Jarry, Tristian',
        playerNum: 35,
        style: 'Away',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsjarry35aw2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.9',
        numReviews: 89,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Tristian Jarry in action. Whether you\'re behind the glass or the TV screen, this Tristian Jarry Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Tristian Jarry\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Tristian Jarry Pittsburgh Penguins Adidas Reverse Retro Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'goalie',
        player: 'Jarry, Tristian',
        playerNum: 35,
        style: 'Reverse Retro',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsjarry35rr2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.8',
        numReviews: 78,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Tristian Jarry in action. Whether you\'re behind the glass or the TV screen, this Tristian Jarry Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Tristian Jarry\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
{
        name: 'Casey DeSmith Pittsburgh Penguins Adidas Home Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'goalie',
        player: 'DeSmith, Casey',
        playerNum: 1,
        style: 'Home',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsdesmith1ho2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.2',
        numReviews: 34,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Casey DeSmith in action. Whether you\'re behind the glass or the TV screen, this Casey DeSmith Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Casey DeSmith\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Casey DeSmith Pittsburgh Penguins Adidas Away Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'goalie',
        player: 'DeSmith, Casey',
        playerNum: 1,
        style: 'Away',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsdesmith1aw2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.3',
        numReviews: 41,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Casey DeSmith in action. Whether you\'re behind the glass or the TV screen, this Casey DeSmith Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Casey DeSmith\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
    {
        name: 'Casey DeSmith Pittsburgh Penguins Adidas Reverse Retro Jersey ',
        category: 'jersey',
        team: 'Pittsburgh Penguins',
        position: 'goalie',	
        player: 'DesSmith, Casey',
        playerNum: 1,
        style: 'Reverse Retro',
        size: 's',
        year: 2021,
        image: '../img/penguins/jsdesmith1rr2021.jpg',
        price: 229.99,
        countInStock: 100,
        brand: 'Adidas',
        rating: '4.4',
        numReviews: 63,
        description: 'You\'re the ultimate Pittsburgh Penguins fan, and nothing is better than watching Casey DeSmith in action. Whether you\'re behind the glass or the TV screen, this Casey DeSmith Authentic Player Jersey from adidas is the perfect way to express your fandom. It features the authentic Pittsburgh Penguins crest on the front and Casey DeSmith\'s name and number on the back, along with PlayDry and X-trafil fabric technologies that maximize comfort and durability, respectively.',
    },
],
}

export default data;